#!/bin/bash
#script for  march 10 with time loss and dealer #

echo "script has been ran sucessfully for march 12  08:00pm"

grep "0312" ./Player_Analysis/Roulette_Losses|grep '08:00:00 PM'|awk '{ print $1,$2,$3 }' >> Dealers_Working_during_losses  
grep '08:00:00 PM' ./Dealer_Analysis/MARCH10ROULETTESCHEDULE |awk '{ print $3,$4 }' >> Dealers_Working_during_losses
